import type { CandidateProfile, JobPosting, PricingPlan } from "./types";

// Placeholder data for local development. Replace with Supabase queries once
// the `candidates` table is live — see the README for the suggested schema.
export const MOCK_CANDIDATES: CandidateProfile[] = [
  {
    id: "1",
    slug: "maria-santos",
    fullName: "Maria Santos",
    title: "Senior Executive Assistant",
    category: "Executive Assistant",
    location: "Cebu City, PH",
    avatarInitials: "MS",
    avatarColorFrom: "from-cyan-400",
    avatarColorTo: "to-blue-500",
    monthlySalaryUsd: 1400,
    hourlyRateUsd: 9,
    yearsExperience: 6,
    softwareSkills: ["ClickUp", "Notion", "Google Ads"],
    hasVideoIntro: true,
    idVerified: true,
    verifiedScore: 96,
    bio: "Ex-agency EA who has run inboxes, calendars, and vendor ops for two US-based CEOs.",
    isContactUnlocked: false,
    createdAt: "2026-06-01",
  },
  {
    id: "2",
    slug: "jc-reyes",
    fullName: "JC Reyes",
    title: "Short-Form Video Editor",
    category: "Video Editing",
    location: "Davao City, PH",
    avatarInitials: "JR",
    avatarColorFrom: "from-fuchsia-400",
    avatarColorTo: "to-cyan-400",
    monthlySalaryUsd: 1600,
    hourlyRateUsd: 11,
    yearsExperience: 4,
    softwareSkills: ["CapCut", "Premiere Pro", "Canva"],
    hasVideoIntro: true,
    idVerified: true,
    verifiedScore: 92,
    bio: "Cuts UGC and TikTok/Reels content for 3 DTC brands doing 7-figure ad spend.",
    isContactUnlocked: false,
    createdAt: "2026-05-18",
  },
  {
    id: "3",
    slug: "angela-cruz",
    fullName: "Angela Cruz",
    title: "E-commerce Operations Manager",
    category: "E-commerce Ops",
    location: "Manila, PH",
    avatarInitials: "AC",
    avatarColorFrom: "from-teal-400",
    avatarColorTo: "to-emerald-500",
    monthlySalaryUsd: 1900,
    hourlyRateUsd: 12,
    yearsExperience: 5,
    softwareSkills: ["Shopify", "Klaviyo", "Zendesk"],
    hasVideoIntro: false,
    idVerified: true,
    verifiedScore: 94,
    bio: "Runs day-to-day Shopify store ops, fulfillment, and Klaviyo flows for a $2M/yr apparel brand.",
    isContactUnlocked: false,
    createdAt: "2026-04-22",
  },
  {
    id: "4",
    slug: "paolo-mendoza",
    fullName: "Paolo Mendoza",
    title: "Bookkeeper & Accounts Manager",
    category: "Finance & Bookkeeping",
    location: "Iloilo City, PH",
    avatarInitials: "PM",
    avatarColorFrom: "from-sky-400",
    avatarColorTo: "to-indigo-500",
    monthlySalaryUsd: 1300,
    hourlyRateUsd: 8,
    yearsExperience: 7,
    softwareSkills: ["Xero", "QuickBooks"],
    hasVideoIntro: true,
    idVerified: true,
    verifiedScore: 98,
    bio: "Certified bookkeeper managing monthly close, AR/AP, and payroll for 4 US-based agencies.",
    isContactUnlocked: false,
    createdAt: "2026-07-02",
  },
  {
    id: "5",
    slug: "ella-domingo",
    fullName: "Ella Domingo",
    title: "Paid Media Buyer",
    category: "Media Buying",
    location: "Quezon City, PH",
    avatarInitials: "ED",
    avatarColorFrom: "from-amber-400",
    avatarColorTo: "to-pink-500",
    monthlySalaryUsd: 2100,
    hourlyRateUsd: 14,
    yearsExperience: 5,
    softwareSkills: ["Meta Ads Manager", "Google Ads", "Shopify"],
    hasVideoIntro: true,
    idVerified: true,
    verifiedScore: 91,
    bio: "Manages $80k/mo in Meta and Google ad spend across 6 e-commerce accounts.",
    isContactUnlocked: false,
    createdAt: "2026-06-29",
  },
  {
    id: "6",
    slug: "ryan-torres",
    fullName: "Ryan Torres",
    title: "Operations & Systems EA",
    category: "Executive Assistant",
    location: "Baguio City, PH",
    avatarInitials: "RT",
    avatarColorFrom: "from-violet-400",
    avatarColorTo: "to-cyan-400",
    monthlySalaryUsd: 1500,
    hourlyRateUsd: 10,
    yearsExperience: 4,
    softwareSkills: ["ClickUp", "Notion", "Zendesk"],
    hasVideoIntro: false,
    idVerified: true,
    verifiedScore: 89,
    bio: "Builds and runs SOPs, ClickUp workflows, and light bookkeeping for a UK marketing agency.",
    isContactUnlocked: false,
    createdAt: "2026-05-11",
  },
];

export const MOCK_JOBS: JobPosting[] = [
  {
    id: "j1",
    slug: "shopify-ecommerce-ops-manager",
    title: "Shopify E-commerce Ops Manager",
    companyName: "Northbound Apparel Co.",
    category: "E-commerce Ops",
    employmentType: "Full-time",
    monthlySalaryMinUsd: 1600,
    monthlySalaryMaxUsd: 2200,
    requiredSkills: ["Shopify", "Klaviyo", "Zendesk"],
    isRemote: true,
    postedAt: "2026-08-05",
    applicantCount: 12,
    description:
      "Own day-to-day store operations, fulfillment, and email flows for a growing DTC apparel brand.",
  },
  {
    id: "j2",
    slug: "short-form-video-editor-ugc",
    title: "Short-Form Video Editor (UGC / Paid Social)",
    companyName: "Loop Media Group",
    category: "Video Editing",
    employmentType: "Part-time",
    monthlySalaryMinUsd: 1000,
    monthlySalaryMaxUsd: 1800,
    requiredSkills: ["CapCut", "Premiere Pro"],
    isRemote: true,
    postedAt: "2026-08-09",
    applicantCount: 27,
    description:
      "Cut fast-turnaround TikTok and Reels content for three e-commerce ad accounts.",
  },
  {
    id: "j3",
    slug: "remote-executive-assistant",
    title: "Executive Assistant to CEO",
    companyName: "Harbor & Vale Consulting",
    category: "Executive Assistant",
    employmentType: "Full-time",
    monthlySalaryMinUsd: 1300,
    monthlySalaryMaxUsd: 1900,
    requiredSkills: ["ClickUp", "Notion"],
    isRemote: true,
    postedAt: "2026-08-11",
    applicantCount: 19,
    description:
      "Manage inbox, calendar, and vendor coordination for a US-based consulting founder.",
  },
  {
    id: "j4",
    slug: "bookkeeper-agency-accounts",
    title: "Bookkeeper — Multi-Client Agency Accounts",
    companyName: "Ledger & Co.",
    category: "Finance & Bookkeeping",
    employmentType: "Full-time",
    monthlySalaryMinUsd: 1100,
    monthlySalaryMaxUsd: 1600,
    requiredSkills: ["Xero", "QuickBooks"],
    isRemote: true,
    postedAt: "2026-08-07",
    applicantCount: 8,
    description:
      "Handle monthly close, AR/AP, and payroll across a portfolio of small agency clients.",
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    priceUsdPerMonth: 0,
    billingNote: "forever",
    description: "Browse the full talent pool and post jobs at no cost.",
    features: [
      "Unlimited talent search & filtering",
      "Post unlimited job listings",
      "View skill badges & verified scores",
      "Contact info & video intros locked",
    ],
    isMostPopular: false,
    ctaLabel: "Get Started Free",
  },
  {
    id: "business",
    name: "Business Pass",
    priceUsdPerMonth: 49,
    billingNote: "per month, billed monthly",
    description: "For founders and managers hiring 1-3 specialists.",
    features: [
      "Everything in Free",
      "Unlock unlimited candidate contact info",
      "Watch full video introductions",
      "Direct in-app messaging",
      "Wise payment setup assistance",
    ],
    isMostPopular: true,
    ctaLabel: "Start Business Pass",
  },
  {
    id: "agency",
    name: "Agency Plan",
    priceUsdPerMonth: 149,
    billingNote: "per month, billed monthly",
    description: "For agencies and teams making recurring hires.",
    features: [
      "Everything in Business Pass",
      "Up to 5 team seats",
      "Priority candidate shortlisting",
      "Dedicated hiring concierge",
      "Early access to new talent pools",
    ],
    isMostPopular: false,
    ctaLabel: "Start Agency Plan",
  },
];
